name: feedparser
version: 0.0.2
description: RSS feed parser.
authors:
- Victor Choueiri <victor.oc@gmail.com>
homepage: https://github.com/xqwzts/feedparser

environment:
  sdk: "=2.3.0 <3.0.0"
dependencies:
  xml: ^3.5.0
  
dev_dependencies:
  test: ^1.6.3
